image: node:6

before_script:
  - npm install
  - npm install sails -g

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test:lint:
  script:
    - sails lift